//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AionRecipeCalculator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AionRecipeCalculator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AionRecipeCalculator", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagger.
        /// </summary>
        internal static string s1 {
            get {
                return ResourceManager.GetString("s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hat.
        /// </summary>
        internal static string s10 {
            get {
                return ResourceManager.GetString("s10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        internal static string s100 {
            get {
                return ResourceManager.GetString("s100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recipe.
        /// </summary>
        internal static string s101 {
            get {
                return ResourceManager.GetString("s101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to craft {0} lvl.
        /// </summary>
        internal static string s102 {
            get {
                return ResourceManager.GetString("s102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string s103 {
            get {
                return ResourceManager.GetString("s103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email for me to reply you.
        /// </summary>
        internal static string s104 {
            get {
                return ResourceManager.GetString("s104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message (English or Portuguese).
        /// </summary>
        internal static string s105 {
            get {
                return ResourceManager.GetString("s105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter email.
        /// </summary>
        internal static string s106 {
            get {
                return ResourceManager.GetString("s106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email address.
        /// </summary>
        internal static string s107 {
            get {
                return ResourceManager.GetString("s107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter message text.
        /// </summary>
        internal static string s108 {
            get {
                return ResourceManager.GetString("s108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been send successfully!&lt;br /&gt;Thank you!.
        /// </summary>
        internal static string s109 {
            get {
                return ResourceManager.GetString("s109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robe armor.
        /// </summary>
        internal static string s11 {
            get {
                return ResourceManager.GetString("s11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending your message....
        /// </summary>
        internal static string s110 {
            get {
                return ResourceManager.GetString("s110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc.
        /// </summary>
        internal static string s111 {
            get {
                return ResourceManager.GetString("s111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non proc.
        /// </summary>
        internal static string s112 {
            get {
                return ResourceManager.GetString("s112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings for current item.
        /// </summary>
        internal static string s113 {
            get {
                return ResourceManager.GetString("s113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string s114 {
            get {
                return ResourceManager.GetString("s114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select recipe.
        /// </summary>
        internal static string s115 {
            get {
                return ResourceManager.GetString("s115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string s116 {
            get {
                return ResourceManager.GetString("s116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leather armor.
        /// </summary>
        internal static string s12 {
            get {
                return ResourceManager.GetString("s12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain armor.
        /// </summary>
        internal static string s13 {
            get {
                return ResourceManager.GetString("s13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate armor.
        /// </summary>
        internal static string s14 {
            get {
                return ResourceManager.GetString("s14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        internal static string s15 {
            get {
                return ResourceManager.GetString("s15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        internal static string s16 {
            get {
                return ResourceManager.GetString("s16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necklace.
        /// </summary>
        internal static string s17 {
            get {
                return ResourceManager.GetString("s17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earrings.
        /// </summary>
        internal static string s18 {
            get {
                return ResourceManager.GetString("s18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring.
        /// </summary>
        internal static string s19 {
            get {
                return ResourceManager.GetString("s19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mace.
        /// </summary>
        internal static string s2 {
            get {
                return ResourceManager.GetString("s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemy.
        /// </summary>
        internal static string s20 {
            get {
                return ResourceManager.GetString("s20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armorsmith.
        /// </summary>
        internal static string s21 {
            get {
                return ResourceManager.GetString("s21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morph.
        /// </summary>
        internal static string s22 {
            get {
                return ResourceManager.GetString("s22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking.
        /// </summary>
        internal static string s23 {
            get {
                return ResourceManager.GetString("s23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handicraft.
        /// </summary>
        internal static string s24 {
            get {
                return ResourceManager.GetString("s24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailoring.
        /// </summary>
        internal static string s25 {
            get {
                return ResourceManager.GetString("s25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weaponsmith.
        /// </summary>
        internal static string s26 {
            get {
                return ResourceManager.GetString("s26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junk.
        /// </summary>
        internal static string s27 {
            get {
                return ResourceManager.GetString("s27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string s28 {
            get {
                return ResourceManager.GetString("s28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior.
        /// </summary>
        internal static string s29 {
            get {
                return ResourceManager.GetString("s29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1H Sword.
        /// </summary>
        internal static string s3 {
            get {
                return ResourceManager.GetString("s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroic.
        /// </summary>
        internal static string s30 {
            get {
                return ResourceManager.GetString("s30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabled.
        /// </summary>
        internal static string s31 {
            get {
                return ResourceManager.GetString("s31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eternal.
        /// </summary>
        internal static string s32 {
            get {
                return ResourceManager.GetString("s32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mythic.
        /// </summary>
        internal static string s33 {
            get {
                return ResourceManager.GetString("s33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a email to me.
        /// </summary>
        internal static string s34 {
            get {
                return ResourceManager.GetString("s34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback/bug report.
        /// </summary>
        internal static string s35 {
            get {
                return ResourceManager.GetString("s35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to aionsource forum disccussion about&amp;lt;br /&amp;gt;this material calculator (in new window).
        /// </summary>
        internal static string s36 {
            get {
                return ResourceManager.GetString("s36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discuss it on forum.
        /// </summary>
        internal static string s37 {
            get {
                return ResourceManager.GetString("s37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload current page without any&amp;lt;br /&amp;gt;recipe selected (in current window).
        /// </summary>
        internal static string s38 {
            get {
                return ResourceManager.GetString("s38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string s39 {
            get {
                return ResourceManager.GetString("s39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2H Sword.
        /// </summary>
        internal static string s4 {
            get {
                return ResourceManager.GetString("s4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recipe selected..
        /// </summary>
        internal static string s40 {
            get {
                return ResourceManager.GetString("s40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        internal static string s41 {
            get {
                return ResourceManager.GetString("s41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See full details at database site (new window).
        /// </summary>
        internal static string s42 {
            get {
                return ResourceManager.GetString("s42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View recipe information.
        /// </summary>
        internal static string s43 {
            get {
                return ResourceManager.GetString("s43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Bug, Suggestion or Additional Translation.
        /// </summary>
        internal static string s44 {
            get {
                return ResourceManager.GetString("s44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me!.
        /// </summary>
        internal static string s45 {
            get {
                return ResourceManager.GetString("s45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aion Recipe Material Calculator.
        /// </summary>
        internal static string s46 {
            get {
                return ResourceManager.GetString("s46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still need {0}.
        /// </summary>
        internal static string s47 {
            get {
                return ResourceManager.GetString("s47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have.
        /// </summary>
        internal static string s48 {
            get {
                return ResourceManager.GetString("s48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for each.
        /// </summary>
        internal static string s49 {
            get {
                return ResourceManager.GetString("s49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polearm.
        /// </summary>
        internal static string s5 {
            get {
                return ResourceManager.GetString("s5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a number.
        /// </summary>
        internal static string s50 {
            get {
                return ResourceManager.GetString("s50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be valid integer number.
        /// </summary>
        internal static string s51 {
            get {
                return ResourceManager.GetString("s51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be greater or equal to zero.
        /// </summary>
        internal static string s52 {
            get {
                return ResourceManager.GetString("s52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability %.
        /// </summary>
        internal static string s53 {
            get {
                return ResourceManager.GetString("s53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the probability of &apos;{0}&apos; successfull craft.
        /// </summary>
        internal static string s54 {
            get {
                return ResourceManager.GetString("s54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid floating-point number.
        /// </summary>
        internal static string s55 {
            get {
                return ResourceManager.GetString("s55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be greater than 1.
        /// </summary>
        internal static string s56 {
            get {
                return ResourceManager.GetString("s56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recipe was found..
        /// </summary>
        internal static string s57 {
            get {
                return ResourceManager.GetString("s57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Aion Recipe Material Calculator.
        /// </summary>
        internal static string s58 {
            get {
                return ResourceManager.GetString("s58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View item information.
        /// </summary>
        internal static string s59 {
            get {
                return ResourceManager.GetString("s59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string s6 {
            get {
                return ResourceManager.GetString("s6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have.
        /// </summary>
        internal static string s60 {
            get {
                return ResourceManager.GetString("s60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data in different format.
        /// </summary>
        internal static string s61 {
            get {
                return ResourceManager.GetString("s61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to edit.
        /// </summary>
        internal static string s62 {
            get {
                return ResourceManager.GetString("s62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string s63 {
            get {
                return ResourceManager.GetString("s63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need.
        /// </summary>
        internal static string s64 {
            get {
                return ResourceManager.GetString("s64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        internal static string s65 {
            get {
                return ResourceManager.GetString("s65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell price for one item.
        /// </summary>
        internal static string s66 {
            get {
                return ResourceManager.GetString("s66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell price for this item. By default vendor&amp;lt;br /&amp;gt;sell price is displayed. Click to edit..
        /// </summary>
        internal static string s67 {
            get {
                return ResourceManager.GetString("s67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total sell price.
        /// </summary>
        internal static string s68 {
            get {
                return ResourceManager.GetString("s68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit (not including &quot;have&quot; materials).
        /// </summary>
        internal static string s69 {
            get {
                return ResourceManager.GetString("s69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb.
        /// </summary>
        internal static string s7 {
            get {
                return ResourceManager.GetString("s7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        internal static string s70 {
            get {
                return ResourceManager.GetString("s70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string s71 {
            get {
                return ResourceManager.GetString("s71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the sell price for &apos;{0}&apos;.
        /// </summary>
        internal static string s72 {
            get {
                return ResourceManager.GetString("s72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BB code.
        /// </summary>
        internal static string s73 {
            get {
                return ResourceManager.GetString("s73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingame code.
        /// </summary>
        internal static string s74 {
            get {
                return ResourceManager.GetString("s74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        internal static string s75 {
            get {
                return ResourceManager.GetString("s75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string s76 {
            get {
                return ResourceManager.GetString("s76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingame link.
        /// </summary>
        internal static string s77 {
            get {
                return ResourceManager.GetString("s77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingame link (need).
        /// </summary>
        internal static string s78 {
            get {
                return ResourceManager.GetString("s78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to each {0} can be {1} crafted with {2} from.
        /// </summary>
        internal static string s79 {
            get {
                return ResourceManager.GetString("s79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string s8 {
            get {
                return ResourceManager.GetString("s8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull craft probability - click to edit.
        /// </summary>
        internal static string s80 {
            get {
                return ResourceManager.GetString("s80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load proc version of this item.
        /// </summary>
        internal static string s81 {
            get {
                return ResourceManager.GetString("s81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load non proc version of this item.
        /// </summary>
        internal static string s82 {
            get {
                return ResourceManager.GetString("s82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need - click to edit.
        /// </summary>
        internal static string s83 {
            get {
                return ResourceManager.GetString("s83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to toggle selection for this item as material&amp;lt;br /&amp;gt;that you will use for current recipe.
        /// </summary>
        internal static string s84 {
            get {
                return ResourceManager.GetString("s84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading recipes....
        /// </summary>
        internal static string s85 {
            get {
                return ResourceManager.GetString("s85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recipes was found..
        /// </summary>
        internal static string s86 {
            get {
                return ResourceManager.GetString("s86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string s87 {
            get {
                return ResourceManager.GetString("s87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elyos.
        /// </summary>
        internal static string s88 {
            get {
                return ResourceManager.GetString("s88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asmodians.
        /// </summary>
        internal static string s89 {
            get {
                return ResourceManager.GetString("s89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bow.
        /// </summary>
        internal static string s9 {
            get {
                return ResourceManager.GetString("s9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string s90 {
            get {
                return ResourceManager.GetString("s90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle ignore case.
        /// </summary>
        internal static string s91 {
            get {
                return ResourceManager.GetString("s91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string s92 {
            get {
                return ResourceManager.GetString("s92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string s93 {
            get {
                return ResourceManager.GetString("s93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft level.
        /// </summary>
        internal static string s94 {
            get {
                return ResourceManager.GetString("s94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item level.
        /// </summary>
        internal static string s95 {
            get {
                return ResourceManager.GetString("s95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity.
        /// </summary>
        internal static string s96 {
            get {
                return ResourceManager.GetString("s96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item level.
        /// </summary>
        internal static string s97 {
            get {
                return ResourceManager.GetString("s97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill level.
        /// </summary>
        internal static string s98 {
            get {
                return ResourceManager.GetString("s98", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset filter.
        /// </summary>
        internal static string s99
        {
            get
            {
                return ResourceManager.GetString("s99", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset filter.
        /// </summary>
        internal static string s122
        {
            get
            {
                return ResourceManager.GetString("s122", resourceCulture);
            }
        }
    }
}
